title: Fineract® Academy
description: unofficial learning space of Apache Fineract®
theme: just-the-docs

url: https://fineract-academy.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
